Project=daq
Package=rubuilder/fu
DynamicLibrary= rubuilderfu

Sources= \
	Application.cc \
	FedSourceIds.cc \
	ForceFailedEvent.cc \
	SynchronizedString.cc \
	version.cc

include ../mfRubuilder.rules

