Project=daq
Package=rubuilder/evm
DynamicLibrary= rubuilderevm

Sources= \
	Application.cc \
	BUproxy.cc \
	DummyTrigger.cc \
	EoLSHandler.cc \
	EVM.cc \
	FEROLhandler.cc \
	GTPehandler.cc \
	L1InfoHandler.cc \
	LumiSectionTable.cc \
	RUproxy.cc \
	SMproxy.cc \
	StateMachine.cc \
	TAhandler.cc \
	TRGproxy.cc \
	version.cc

include ../mfRubuilder.rules

