Project=daq
Package=rubuilder/bu
DynamicLibrary= rubuilderbu

Sources= \
	Application.cc \
	BU.cc \
	DiskUsage.cc \
	DiskWriter.cc \
	Event.cc \
	EventTable.cc \
	EVMproxy.cc \
	FileHandler.cc \
	FUproxy.cc \
	LumiHandler.cc \
	RUproxy.cc \
	StateMachine.cc \
	version.cc

include ../mfRubuilder.rules

