Project=daq
Package=rubuilder/utils
DynamicLibrary= rubuilderutils

Sources= \
	ApplicationInstanceLess.cc \
	DumpUtility.cc \
	EvBidFactory.cc \
	EventUtils.cc \
	FragmentSets.cc \
	InfoSpaceItems.cc \
	I2OMessages.cc \
	RUbroadcaster.cc \
	SuperFragmentGenerator.cc \
	SuperFragmentTracker.cc \
	TimerManager.cc \
	UnsignedInteger32Less.cc \
	WebUtils.cc \
	XoapUtils.cc \
	CreateStrings.cc \
	version.cc

DependentLibraries = interfaceshared
DependentLibraryDirs = $(INTERFACE_SHARED_LIB_PREFIX)

include ../mfRubuilder.rules

