#!/usr/bin/perl

use strict;

die "Usage getParam host port class instance paramName paramType\n" if @ARGV != 6;

my $host      = $ARGV[0];
my $port      = $ARGV[1];
my $class     = $ARGV[2];
my $instance  = $ARGV[3];
my $paramName = $ARGV[4];
my $paramType = $ARGV[5];

my $m = "";
$m .= '<SOAP-ENV:Envelope';
$m .= ' SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"';
$m .= ' xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"';
$m .= ' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"';
$m .= ' xmlns:xsd="http://www.w3.org/2001/XMLSchema"';
$m .= ' xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"';
$m .= '>';
$m .=   '<SOAP-ENV:Header>';
$m .=   '</SOAP-ENV:Header>';
$m .=   '<SOAP-ENV:Body>';
$m .=     '<xdaq:ParameterGet';
$m .=     ' xmlns:xdaq="urn:xdaq-soap:3.0"';
$m .=     '>';
$m .=       '<p:properties';
$m .=       ' xmlns:p="urn:xdaq-application:CLASS"';
$m .=       ' xsi:type="soapenc:Struct"';
$m .=       '>';
$m .=         '<p:PARAM_NAME';
$m .=         ' xsi:type="xsd:PARAM_TYPE"';
$m .=         '/>';
$m .=       '</p:properties>';
$m .=     '</xdaq:ParameterGet>';
$m .=   '</SOAP-ENV:Body>';
$m .= '</SOAP-ENV:Envelope>';

$m =~ s/CLASS/$class/g;
$m =~ s/PARAM_NAME/$paramName/g;
$m =~ s/PARAM_TYPE/$paramType/g;

$m =~ s/"/\\\"/g;

my $curlCmd  = "curl --stderr /dev/null -H \"Content-Type: text/xml\" -H \"Content-Description: SOAP Message\" -H \"SOAPAction: urn:xdaq-application:class=$class,instance=$instance\" http://$host:$port -d \"$m\"";

open CURL, "$curlCmd|";

my $reply = "";

while(<CURL>) {
  chomp;
  $reply .= $_;
}

if($reply =~ m#<\w+:$paramName\s[^>]*>([^<]*)</\w+:$paramName>#) {
  my $paramValue = $1;
  print "$paramValue\n";
  exit 0;
} elsif($reply =~ m#<\w+:$paramName\s[^>]*/>#) {
  print "\n";
} else {
  print "ERROR";
  print " COMMAND=";
  print "$m\n";
  print " REPLY=";
  if($reply eq "") {
    print "NONE\n";
  } else {
    print "$reply\n";
  }
  exit 1;
}
