#!/usr/bin/perl -w


use IO::Socket;

die "Usage getXDAQStatus farmFile\n" if @ARGV != 1;

$farmFile = $ARGV[0];

die "The file \"$farmFile\" does not exist\n" unless -e $farmFile;

while(<>)
{
  chomp;
  ($host, $port) = split / /;

  $socket = IO::Socket::INET->new(PeerAddr => $host,
                                  PeerPort => $port,
                                  Proto    => "tcp",
                                  Type     => SOCK_STREAM);

  if($socket) {
    print $socket "GETXDAQSTATUS\n";

    $reply = <$socket>;

    print "$host $port: $reply";

    close($socket);
  } else {
    print "$host $port: Failed to connect: $@\n";
  }
}
