#!/usr/bin/perl

die "Usage produceConfigureCmd configurationFile\n" if @ARGV != 1;
$configuration = $ARGV[0];
die "The file \"$configuration\" does not exist\n" unless -e $configuration;

print "<soap-env:Envelope\n";
print " soap-env:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"\n";
print " xmlns:soap-env=\"http://schemas.xmlsoap.org/soap/envelope/\"\n";
print " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n";
print " xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"\n";
print " xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\">\n";
print "<soap-env:Header>\n";
print "</soap-env:Header>\n";
print "<soap-env:Body>\n";
print "<xdaq:Configure xmlns:xdaq=\"urn:xdaq-soap:3.0\">\n";

open CONFIGURATION, "<$configuration";
while(<CONFIGURATION>) {
  print;
}
close CONFIGURATION;

print "</xdaq:Configure>\n";
print "</soap-env:Body>\n";
print "</soap-env:Envelope>\n";
