#!/bin/sh -e

if test x${TESTS_SYMBOL_MAP} = x
then
  echo "Error : TESTS_SYMBOL_MAP has not been set - Aborting"
  exit 1
fi

if test ! -e $TESTS_SYMBOL_MAP
then
  echo "The file $TESTS_SYMBOL_MAP (value of TESTS_SYMBOL_MAP) does not exist"
  exit 1
fi

if test ! -f $TESTS_SYMBOL_MAP
then
  echo "$TESTS_SYMBOL_MAP (value of TESTS_SYMBOL_MAP) is not a regular file"
  exit 1
fi

if test $# -ne 1
then
  echo "Usage: runTest testName"
  exit 1
fi

testDir="${RUB_TESTER_HOME}/cases/$1"

if test ! -e $testDir
then
  echo "The directory $testDir does not exist"
  exit 1
fi

if test ! -d $testDir
then
  echo "$testDir is not a directory"
  exit 1
fi

localTestDir="${RUB_TESTER_HOME}/${XDAQ_PLATFORM}/$1"
mkdir -p $localTestDir
cd $localTestDir

cp $testDir/*.xml .
rm -f *template.xml

echo "Producing configuration file"
fillTemplate $testDir/configuration.template.xml > configuration.xml

echo "Producing configuration command file"
produceConfigureCmd configuration.xml > configure.cmd.xml

echo "Producing control script file"
fillTemplate $testDir/controlScript.template.sh > controlScript.sh

chmod +x controlScript.sh

stopXDAQs

echo "Running the RU builder"
./controlScript.sh
