#!/usr/bin/perl -w

use strict;

my $testDir = $ENV{RUB_TESTER_HOME};
my $symbolMap = $ENV{"TESTS_SYMBOL_MAP"};
my $testEnv = "";
$testEnv = "-" . $ENV{"TEST_TYPE"} if $ENV{"TEST_TYPE"};

die "The file \"$symbolMap\" does not exist\n" unless -e $symbolMap;

my $port = 12222;
my $hostname=lc(`hostname -f`);
chomp $hostname;

open SYMBOL_MAP_FILE, "<$symbolMap";
while(<SYMBOL_MAP_FILE>) {
  chomp;
  if(m/^LAUNCHER_BASE_PORT\s+([A-Za-z0-9_.\-\/:][ ()A-Za-z0-9_.\-\/:]+)/) {
    $port = $1;
  } elsif(m/^([A-Za-z0-9_]+)SOAP_HOST_NAME\s+([A-Za-z0-9_.\-\/:][ ()A-Za-z0-9_.\-\/:]+)/) {
    my $hostType  = $1;
    my $host = $2;
    $host =~ s/localhost/$hostname/;

    my $sshCmd      = "ssh -x -n $host";
    my $launcherCmd = "cd /tmp && rm -f /tmp/core.* && source $testDir/setenv$testEnv.sh && xdaqLauncher $port";
    my $awkCmd      = "awk '{print \"$host:$port \" \$0}'";
    my $cmd         = "$sshCmd \"sudo -u mommsen sh -c \\\"$launcherCmd\\\"\" | $awkCmd &";

    print "$cmd\n";
    system $cmd;

    $port++;
  }
}
