#!/usr/bin/perl -w

use IO::Socket;
use strict;

my $symbolMap = $ENV{"TESTS_SYMBOL_MAP"};

die "The file \"$symbolMap\" does not exist\n" unless -e $symbolMap;

my $port = 12222;
my $hostname=lc(`hostname -f`);
chomp $hostname;

open SYMBOL_MAP_FILE, "<$symbolMap";
while(<SYMBOL_MAP_FILE>) {
  chomp;
  if(m/^LAUNCHER_BASE_PORT\s+([A-Za-z0-9_.\-\/:][ ()A-Za-z0-9_.\-\/:]+)/) {
    $port = $1;
  } elsif(m/^[A-Za-z0-9_]+SOAP_HOST_NAME\s+([A-Za-z0-9_.\-\/:][ ()A-Za-z0-9_.\-\/:]+)/) {
    my $host = $1;
    $host =~ s/localhost/$hostname/;
    
    system "sendCmdToLauncher $host $port STOPXDAQ";
    
    $port++;
  }
}
