Project=daq
Package=rubuilder/ru
DynamicLibrary= rubuilderru

Sources= \
	Application.cc \
	BUproxy.cc \
	DummyInputData.cc \
	EVMproxy.cc \
	FBOproxy.cc \
	FEROLproxy.cc \
	FEROL2proxy.cc \
	RU.cc \
	RUinput.cc \
	StateMachine.cc \
	SuperFragment.cc \
	SuperFragmentTable.cc \
	version.cc

include ../mfRubuilder.rules

